### ISSUE TITLE
Root path not supported

### ISSUE THREAD

**Issue by themightychris** [jorith88/vscode-webdav#1]
When my `webdav.json` looks like this:

```json
{
    "/": {
        "url": "http://example.org/webdav/"
    }
}
```

I get this error when I try to upload:
> Cannot find a remote endpoint configuration for the current working directory /foo/bar in webdav.json...

To workaround I have to add a mapping for every top-level directory in my workspace

**Comment by jorith88** [comment]
Hi Chris,

Thanks for reporting the issue. It will be solved in the next release.

Jorith
