### ISSUE TITLE
Initialize connection 

### ISSUE THREAD

**Issue by jtwiest** [jorith88/vscode-webdav#2]
I see you pushed a fix for root path support (which I also needed) however I'm having a hard time 'kicking off' the connection with the WebDav server. I've created the file as stated in the readme but haven't figured out how to trigger the connection.

Any advice?

**Comment by jorith88** [comment]
Hi Tyler,

You don't have to set up the connection before uploading or comparing a file. The command itself will connect automatically, so creating the webdav.json should be enough.

Jorith
