### ISSUE TITLE
Not sure how this works.

### ISSUE THREAD

**Issue by SeraVault** [jorith88/vscode-webdav#29]
I installed and setup a WebDAV connection.  Now I'm not sure how I make use of that in VSC. There's no command, there's no menu option.  How does this work?  Thanks!

**Comment by jorith88** [comment]
You should have two extra commands in Code, see the screenshot below. If you select one of these commands it will upload/compare the file you're currently editing to the WebDAV endpoint.

![image](https://user-images.githubusercontent.com/2497310/43722830-7c0a591a-9996-11e8-8eab-0fcf466a3ef8.png)

You should also have an upload button in the status bar:
![image](https://user-images.githubusercontent.com/2497310/43723017-f3a3c7a4-9996-11e8-8485-c143d18f2421.png)

**Comment by SeraVault** [comment]
Thanks!
